modality:
  genomic:
    max_freq: 1
    freq_bands: 3
    freq_base: 2
    additional_dim: 135595
    modality_latent_len: 128
    modelity_weight: 1
    token_fusion_topk_ratio: 0.1
  image:
    max_freq: 1
    freq_bands: 3
    freq_base: 2
    additional_dim: 109
    modality_latent_len: 128
    modelity_weight: 1
    token_fusion_topk_ratio: 0.1
  biospecimen:
    max_freq: 1
    freq_bands: 3
    freq_base: 2
    additional_dim: 147
    modality_latent_len: 128
    modelity_weight: 1
    token_fusion_topk_ratio: 0.1
  clinical:
    max_freq: 1
    freq_bands: 3
    freq_base: 2
    additional_dim: 1496
    modality_latent_len: 128
    modelity_weight: 1
    token_fusion_topk_ratio: 0.1


network_type: MultimodalTransformerUniTokenFusionV4

network:
  hidden_size: 32
  latent_length: 64
  n_heads: 16
  n_blocks: 1
  dropout_rate: 0.1
  mlp_ratio: 2
  fusion_type: max
  num_experts: 4
  topk: 2
  pred_dim: 3
  n_mult_layer: 1